let button1 = document.querySelector(".button1")
let button2 = document.querySelector(".button2")
let h2 = document.querySelector("h2")
let h1 = document.querySelector("h1")
let side1 = document.querySelector(".side1")
let side2 = document.querySelector(".side2")
let side3 = document.querySelector(".side3")
let side4 = document.querySelector(".side4")
let side5 = document.querySelector(".side5")
let menu1 = document.querySelector(".menu1")
let menu2 = document.querySelector(".menu2")
let menu3 = document.querySelector(".menu3")
let text2 = document.querySelector(".text2")
let text1 = document.querySelector(".text1")
let text3 = document.querySelector(".text3")
let text4 = document.querySelector(".text4")
let text5 = document.querySelector(".text5")
let text6 = document.querySelector(".text6")
let text7 = document.querySelector(".text7")
let text8 = document.querySelector(".text8")
let text9 = document.querySelector(".text9")
let text10 = document.querySelector(".text10")
let text11 = document.querySelector(".text11")
let slide = document.querySelector(".slidetitle")
let special = document.querySelector(".special")
let eating  = document.querySelector(".Eating")
let video  = document.querySelector(".video")
let button3  = document.querySelector(".button3")
let about = document.querySelector(".about")


button1.onclick=function(){
  button1.style.display = "block"
  button2.style.display = "block"
  eating.style.display = "block"
  side1.style.display = "none"
  side2.style.display = "none"
  side3.style.display = "none"
  side4.style.display = "none"
  side5.style.display = "none"
  menu1.style.display = "none"
  menu2.style.display = "none"
  menu3.style.display = "none"
  text2.style.display = "none"
  text1.style.display = "none"
  text3.style.display = "none"
  text4.style.display = "none"
  text5.style.display = "none"
  text6.style.display = "none"
  text7.style.display = "none"
  text8.style.display = "none"
  text9.style.display = "none"
  text10.style.display = "none"
  text11.style.display = "none"
  special.style.display = "none"
  slide.style.display = "none"
  video.style.display = "block"
  about.style.display = "none"
}



button2.onclick=function(){
  button1.style.display = "block"
  button2.style.display = "block"
  side1.style.display = "block"
  side2.style.display = "block"
  side3.style.display = "block"
  side4.style.display = "block"
  side5.style.display = "block"
  menu1.style.display = "block"
  menu2.style.display = "block"
  menu3.style.display = "block"
  text2.style.display = "block"
  text1.style.display = "block"
  text3.style.display = "block"
  text4.style.display = "block"
  text5.style.display = "block"
  text6.style.display = "block"
  text7.style.display = "block"
  text8.style.display = "block"
  text9.style.display = "block"
  text10.style.display = "block"
  text11.style.display = "block"
  special.style.display = "block"
  slide.style.display = "block"
  eating.style.display = "none"
  video.style.display = "none"
  about.style.display = "none"
}


button3.onclick=function(){
  button1.style.display = "block"
  button2.style.display = "block"
  eating.style.display = "none"
  side1.style.display = "none"
  side2.style.display = "none"
  side3.style.display = "none"
  side4.style.display = "none"
  side5.style.display = "none"
  menu1.style.display = "none"
  menu2.style.display = "none"
  menu3.style.display = "none"
  text2.style.display = "none"
  text1.style.display = "none"
  text3.style.display = "none"
  text4.style.display = "none"
  text5.style.display = "none"
  text6.style.display = "none"
  text7.style.display = "none"
  text8.style.display = "none"
  text9.style.display = "none"
  text10.style.display = "none"
  text11.style.display = "none"
  special.style.display = "none"
  slide.style.display = "none"
  video.style.display = "none"
  about.style.display = "block"
}